name: Code Quality
on: [push]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
      - run: yarn lint
      - run: yarn check
      - run: yarn test
      - uses: codecov/codecov-action@v3
        with:
          verbose: true
